- schemes/Material-Theme.tmTheme
I wonder if we could add another color for escaped chararacters, since it stands out in Regular Expression and some other cases like this.
Though I'm not sure this would be the right color to use.
> Stands out escaped characters for clarity

- Material-Theme-Darker.sublime-theme
- Material-Theme.sublime-theme
I think the assets root path for the theme should correspond to the one on Package Control.
Here's what I've encountered.
> Fix assets path for package control

- Material-Theme-Darker.sublime-theme
- Material-Theme.sublime-theme
This PR will fix an issue where invisible close buttons are still active on tabs that are new or not dirty when using `show_tab_close_buttons: false`.
annoyingly it seems the dirty indicator has to function like a close button, but at least the close button will warn you if you accidentally try to close a dirty file.
> Support for dirty state w/show_tab_close_buttons

- schemes/Material-Theme.tmTheme
This will turn on highlighting of the active indentation guide as well as the stacked, or parent, indentation guides.
"indent_guide_options":
[
"draw_normal",
"draw_active"
],
Reference 
http://wesbos.com/sublime-text-indentation-guide-lines/
> Enable better highlighting of active indent

- Material-Theme.sublime-theme
Hi,
I'm using Vintage mode, and I navigate sidebar with keyboard (Focus with Ctrl + 0 and navigate).
Files are highlighted when selected with white font color, but folders are not highlighted at all, so you cannot know on which folder focus is at the moment when you are navigating. This PR adds highlight with white font color and folder hover image. Here's the screenshot:
> Highlight sidebar folder on select with keyboard.

- messages/install.txt
This basically removes `**` from each of the separating lines. That's helpful because Package Control prepends every line in the messages window with two spaces.
This also fixes the commas in the recommended settings section.
> Adjusting install.txt to actually fit into the 80 columns

- README.md
https://github.com/equinusocio/material-theme/blame/master/README.md#L69
I found that this line comment position is different from the other lines. The reason is that this line contained tab. So I removed tabs and add spaces.
> Remove tab and add space from README.md

- Material-Theme-Darker.sublime-theme
Hello and thank you for the awesome job on this theme :)
I think I've found a little bug in the "darker" version of the theme where the auto_complete popup seems to have a white background. This background is visible a very short instant when you trying to close the auto_complete popup with "esc" for example.
Thank you and keep the good work :+1:
> Resolve a "white background" bug on autocomplete popup (Darker version)

- schemes/Material-Theme-Darker.tmTheme
- schemes/Material-Theme-Lighter.tmTheme
- schemes/Material-Theme.tmTheme
JS file and Ruby files' REGEX display in different kind of format.
I prefer the first example of JS files for the escaped characters to stand out, so I modified the color to match it. Thanks for you time.
> Unify escaped charactors color in REGEX

- messages/install.txt
Simple syntax error that doesn't allow straight copying and pasting of recommended settings.
> Missing comma in recommended settings JSON

- schemes/Material-Theme-Darker-OceanicNext.tmTheme
- schemes/Material-Theme-Darker.tmTheme
- schemes/Material-Theme-OceanicNext.tmTheme
- schemes/Material-Theme.tmTheme
Add a border to selection to Dark and Normal themes, so the selection
is more visible when present in large text.
> Add Border to current selection so selection is more visible

- README.md
The current Package Control badge provider doesn't show the right amount of downloads, isn't refreshed as often and might not be maintained for very long.
I changed it to Shields.io. The only issue is the badge color cannot be overridden right now, but it is in the works ( see [this PR](https://github.com/badges/shields/pull/547) ). I added the color parameter to the badge so it will work as soon as they support it.
> Change Package Control badge in Readme

- schemes/Material-Theme-Darker-OceanicNext.tmTheme
- schemes/Material-Theme-Darker.tmTheme
- schemes/Material-Theme-Lighter.tmTheme
- schemes/Material-Theme-OceanicNext.tmTheme
- schemes/Material-Theme.tmTheme
Fix different colors for instance variables in Ruby on Rails
From:
To
> Fix instance variable different color in RoR

- schemes/Material-Theme-Darker-OceanicNext.tmTheme
- schemes/Material-Theme-Darker.tmTheme
@equinusocio Pull Request to correct the HTML tag colour in PHP documents. Also lightened comments slightly for readability.
Let me know any thoughts you have here and if you need assistance elsewhere.
> fix html tag colorus in php files | lighten comment strings slightly

- langs/Babel JSON.xml
- langs/ESLint JSON.tmLanguage
Support for ESLint and Babel config file types (`.eslintrc` and `.babelrc`) for JSON syntax highlighting:
> Support for ESLint and Babel config file types

- langs/Babel JSON.xml
- langs/ESLint JSON.tmLanguage
- prefs/icon_gruntfile.tmPreferences
Support so you’re able to comment/uncomment `Gruntfile.js` via the CMD+/ (Mac) or CTRL+/ (Windows) keyboard shortcut
> Gruntfile keyboard shortcut commenting support

- schemes/Material-Theme-Lighter.tmTheme
I thought I should try fixing #749 myself, since it's just an xml file!
Before:
After:
**Edit** I probably should've given my commit a more useful comment like saying that it fixes my issue. Sorry.
> Make lighter's activeGuide easier to see

- schemes/Material-Theme-Darker.tmTheme
- schemes/Material-Theme-Lighter.tmTheme
- schemes/Material-Theme.tmTheme
Fixes #810 
Couldn't find the correct part to update for the OceanicNext themes. But resolves the issue in the base themes
> Italicise id tags in HTML

- dependencies.json
The JSON specification doesn't support comments in `.json` files, so this removes them from `dependencies.json`.
Package control cannot parse the `dependencies.json` file because comments are invalid JSON.
https://github.com/equinusocio/material-theme/issues/925
> Removed comments from dependencies.json

- mt_config.py
I updated the theme configurator script to sort the menu names and options prior to being displayed.
This would improve readability when viewing the theme configurator.
I tested this in Sublime using the modified theme to ensure it worked as expected.
> Sort theme configurator menu names and options

- .src/themes/darker/options.json
- .src/themes/default/options.json
- .src/themes/lighter/options.json
- Material-Theme-Darker.sublime-theme
- Material-Theme-Lighter.sublime-theme
- Material-Theme.sublime-theme
- README.md
Fixes disabled folder animations for all themes. Disabled folder animation code for all accent colours were added back that was deleted in b7446c299a4b0700d56be791eb3efabd9b8bd674. Also adds missing disabled folder animation code for the newer accent colours. Little bit of spelling also fixed in the README.
b7446c299a4b0700d56be791eb3efabd9b8bd674 did not actually fix #943 properly. I noticed that even when I had folder animations disabled and using the dark or light theme, the animations were still there. Additionally, on the default theme, all accents would have the default teal coloured folder when hovering over with folder animations disabled (see screenshot).
I installed the changed theme over the old themes and then checked most of the accents on each of the themes to ensure that …
> Fix disabled folder animations for all themes

- Preferences.sublime-settings
Changed `// Hide headin titles from the sidebar (only with Material Theme Appbar)` to `// Hide heading titles from the sidebar (only with Material Theme Appbar)` (line 121)
I was going through the code, saw a typo, fixed it. Nothing major.
> Fixed typo in Preferences.sublime-settings

- Icons.py
From https://github.com/ihodev/a-file-icon/issues/64#issuecomment-272383883
Shows next popup right after first `Material Theme` installation and if `A File Icon` isn't installed:
```
Material Theme requires `A File Icon` package for enhanced
support of the file-specific icons.
Would you like to install it?
[Install] [Cancel]
```
Install `Material Theme` on fresh Sublime Text.
> Add optional `A File Icon` installer

- README.md
Add my port of the Material Themes to [Base16](https://github.com/chriskempson/base16).
I adapted each of the four themes specified in this project into Base16 color schemes. 
Providing schemes for [Base16](https://github.com/chriskempson/base16) allows color themes to be generated for a variety of tools.
No impact on this repo.
Schemes tested with Base16 builder and verified in a few generated color themes.
Color pallettes used by these themes:
Material
Material Darker
Material Palenight
Material Lighter
> Add Base16 port

- README.md
Simply changed column headers in the color palette table.  
The darker colors were listed under "lighter" and vice versa.
N/A
N/A
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ N/A ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
> correct column headings in README table

- README.md
- sources/themes/commons/accent.json
- utils/config.py
I created a new setting “material_theme_accent_titlebar” to colorize the title bar via chosen accent color (background and foreground).  Also added it to the README file and removed some extra spaces in the settings.
This would provide the ability to change the title bar color, so it matches the accent used throughout the theme.  This would also work with the App Bar to mix or match accents (see issue on missing colors https://github.com/equinusocio/material-theme-appbar/issues/52).
The setting was tested using PackageDev, NPM, and Gulp to compile and view the modified theme.  The README file was tested using dillinger.io markdown editor.
> Add title bar accent config option

- schemes/Material-Theme-Darker.tmTheme
- schemes/Material-Theme-Lighter.tmTheme
- schemes/Material-Theme-Palenight.tmTheme
- schemes/Material-Theme.tmTheme
- sources/schemes/scheme.YAML-tmTheme
This fixes LaTeX live math preview not rendering properly, and updates all popup styles using popupCss. 
This reverts to popupCss, which compiles better and causes the live math preview to render properly via phantomCss used in LaTeX Tools.  This also updates popup styles in the theme (i.e. configurator, code definitions).
Refer to Issue #1209.
The live math preview was tested in a sample .tex file using LaTeX and LaTeX Tools.
The schemes were tested using PackageDev, NPM, and Gulp.
Default
Darker
Palenight
Lighter
Configurator using PopupCss:
> Fix popup styles

- dependencies.json
Updated the dependencies JSON file to add missing dependencies required by the latest version of mdpopups.  
This fixes the issue not enabling theme activation after installation, which many users have experienced using the latest version of Sublime. 
https://github.com/equinusocio/material-theme/issues/1229
This was tested by removing the theme's dependencies in the Packages folder, which disabled theme activation and other options in the Preferences -> Package Settings -> Material Theme menu, except the advanced configuration option.  Then, I restarted Sublime a few times and Package Control installed those dependencies automatically.  This enabled the greyed out menu options as a result.
> Fix theme not activating after installation
