messages/install.txt
Add the Recommended UI and font settings for the install text
=> Update Install.txt with Recommended UI and font settings

README.md
this setting is required for showing the active indent
=> option to enable Highlighting active indent

messages/install.txt
this setting is required for showing the active indent
=> added option for highlighting Active Indent

.editorconfig
Hi @equinusocio , 
To standardize spacing and consistency of coding style I propose using .editorconfig in project.
=> add .editorconfig in project for consistency of coding style

Material-Theme-Darker.sublime-theme, Material-Theme.sublime-theme
Just noticed a slight type with opacity in the theme files.
=> FIXED: Typo with opacity in .sublime-theme files

README.md, messages/install.txt
Improved consistency and readability between README.md and install.txt, Improved readability of install.txt as well. Included information on other theme options in install.txt directly from the README.md.
=> Improved consistency between README.md and install.txt

README.md
I've created [another version][1] of your theme for GitHub's Atom editor. Therefore I thought it might be a great idea to link it here, too (along with the existing one).
[1]: https://atom.io/themes/material-ui
=> Add new port for Atom

schemes/Material-Theme-Darker.tmTheme, schemes/Material-Theme-Lighter.tmTheme, schemes/Material-Theme.tmTheme
Fixed red colored variables, applied few corrections functions and keywords.
For light version I only applied variable color fix.
=> Correction of colors (default, dark, light) (fixes #299)

README.md
[ConEmu](http://conemu.github.io/) is a console emulator for Windows.
=> Add ConEmu port to README

schemes/Material-Theme-Darker-OceanicNext.tmTheme, schemes/Material-Theme-Darker.tmTheme, schemes/Material-Theme-Lighter.tmTheme, schemes/Material-Theme-OceanicNext.tmTheme, schemes/Material-Theme.tmTheme
seriously, let's make the Find Result page more friendly, you can change the colours (as you're more familiar with your theme colours) 
Thanks in advance.
=> add some styling to the Find Results page

README.md
I put in ```font_options``` the ```subpixel_antialias``` for Windows users
=> Update font settings for a better experience on Windows

schemes/Material-Theme.tmTheme
=> Fix for HTML tags in PHP files.

README.md
Adds missing quotes in font used section
=> Add missing quotes (README)

dependencies.json
=> Specify correct dependencies

README.md
Minor fix for formatting issue in main README.
The use of the `<kbd>` tag to format keyboard keys was implemented incorrectly. This has been fixed.
Visually improve the README file.
No tests needed.
=> Fix minor key formatting issue

Material-Theme-Darker.sublime-theme, Material-Theme-Lighter.sublime-theme, Material-Theme-Palenight.sublime-theme, Material-Theme.sublime-theme, sources/themes/darker/overlay_panels.json, sources/themes/default/overlay_panels.json, sources/themes/lighter/overlay_panels.json, sources/themes/palenight/overlay_panels.json
This is an extremely minor PR.
I'm drinking at work and thought "maybe I should submit my first pull request..."
One update across 8 files: "comman" is now "command"
=> minor spelling fix

README.md
=> Add iTerm2 Theme Version

README.md
=> script in html render

README.md
Added Palenight theme for iTerm2
The Palenight theme is not currently an option under the listed iTerm2 porting.
=> Added iTerm2 palenight theme to readme

utils/config.py
The main menu title is rewritten and formatted to all caps.  The accent, panel, sidebar, and tab menu titles have "Material Theme -" text removed.  The color scheme and theme menu titles have "- Material Theme" text removed.
These changes emphasize the main menu title better.  They also make the main menu options and their respective menu titles consistent.
This has been tested in Sublime by using the modified theme to ensure it worked as expected.
=> Update configurator menu titles

CHANGELOG.md, messages.json, messages/install.md, messages/recent.md
Updated the installation and release messages.  Also included the breaking change missing in the changelog.  Forgot to include them in the release, sorry about that.
=> chore: update messages and changelog

.gulp/tasks/bump.js, CHANGELOG.md, Preferences.sublime-settings, README.md, messages.json, messages/recent.md, package-lock.json, package.json, utils/info.py
Bumped version number and added the latest changelog messges.  Made some minor readme tweaks, and updated the preferences file to be in sync with the latest settings.  Also updated the gulp bump task, so it would update the version in both package.json and package-lock.json files.   
This should prepare for release 4.1.4.
=> Release 4.1.4

Preferences.sublime-settings
=> Minor preferences tweak

CHANGELOG.md, messages.json, messages/recent.md, package-lock.json, package.json, utils/info.py
Bumped version number and added changelog messages.
=> Release 4.1.5
